language: perl

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y lighttpd php5 php5-cgi php5-cli php5-curl php5-sqlite

install:
  - (cd t && ./install-wiki.sh install)
  - git clone --depth=1 https://github.com/git/git
  - pwd
  - echo "TEST_DIRECTORY=$(pwd)/git/t" >> /home/travis/build/Git-Mediawiki/Git-Mediawiki/t/test.config

script:
  - make test
